include:
  - project: 'hotmine/infrastructure/CI-CD'
    ref: master
    file: '.gitlab/workflows/master-deploy.yml'
    inputs:
      release: true

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"
