regenerate: true
lang: 'en.yml'
usePlayerLanguage: true
# LEGACY/ENHANCED_LEGACY/MINI_MESSAGE
serializer: MINI_MESSAGE
# OFF/FATAL/ERROR/WARN/INFO/DEBUG/TRACE/ALL
log-level: INFO

multiplier:
  default:
    multiplier: 1.0
    permission: 'group.default'

# https://jd.papermc.io/paper/1.16.5/org/bukkit/entity/EntityType.html
# ANY/ANIMALS/MONSTERS/AMBIENT/WATER_ANIMALS
drop:
  ANIMALS: 1.0..3.0
  MONSTERS: 5.0..10.0
  PIG: 20.0..55.0
