name: Release plugin

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string
      name:
        description: 'Release name'
        required: true
        type: string
      body:
        description: 'Release body'
        required: false
        type: string
      latest:
        description: 'Make release latest'
        default: false
        required: false
        type: boolean

jobs:
  release:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          commit: ${{ github.ref_name }}
          name: ${{ inputs.name }}
          body: ${{ inputs.body }}
          artifacts: build/libs/*.jar
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: ${{ inputs.latest }}
